# Site settings
title: Giulia Zabarella - Index of a biography
short_title: Giulia Zabarella
email: giuliazabarella@proton.me
description: "Giulia Zabarella is a visual artist based between Munich (DE) and Paris (FR)."
url: "http://indexofabiography.de"

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

collections:
 works:
  permalink: /:collection/:title/
  output: true

defaults:
  -
    scope:
      path: ""
      type: "works"
    values:
      layout: work
      categories: works

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
